name: Node.js CI
on: workflow_dispatch

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: git config user.name "user-action"
      - run: git config user.email "with2p@yandex.ru"
      - run: npm install
      - run: npm run build
      - run: npm run deploy
