name: Node.js CI
on:
  push:
    branches:
      - master

workflow_dispatch:
  inputs:
    logLevel:
      description: 'Log level'
      required: true
      default: 'warning'
    tags:
      description: 'Test scenario tags'

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm install
      - run: npm start
      - run: npm run build
